theme: jekyll-theme-minimal

title: QuPath
description: Quantitative Pathology & <span class="wraptastefully">Bioimage Analysis</span>

# logo: images/qupath_128.png
logo: images/qupath-banner-web-logo.jpg

qupath_version: 0.2.3

show_downloads: true

github:
  win_url: https://github.com/qupath/qupath/releases/download/v0.2.3/QuPath-0.2.3-Windows.msi
  mac_url: https://github.com/qupath/qupath/releases/download/v0.2.3/QuPath-0.2.3-Mac.pkg
  linux_url: https://github.com/qupath/qupath/releases/download/v0.2.3/QuPath-0.2.3-Linux.tar.xz

  source_url: https://github.com/qupath/qupath
  docs_url: http://qupath.readthedocs.io
  discuss_url: https://forum.image.sc/tags/qupath
